### ISSUE TITLE
Possible improvement of the default requestGetAttributeMapping for "site"

### ISSUE THREAD

**Issue by ervaude** [sascha-egerer/phpstan-typo3#112]
Hi,
I just noticed, that `$request->getAttribute('site')` is by default configured to return a Site object. The attribute could, however, also hold an instance of `NullSite`, so I reconfigured the `requestGetAttributeMapping` for site in our projects to the `SiteInterface`.

```
parameters:
    typo3:
        requestGetAttributeMapping:
            site: TYPO3\CMS\Core\Site\Entity\SiteInterface
```
Maybe you want to adjust the default configuration? Note, that this would likely lead to some new error reports for people, so if you don't want to do it, just close this issue :)

Thanks for this great package, we use it a lot.

Cheers
