### ISSUE TITLE
Add earlyTerminatingMethodCalls

### ISSUE THREAD

**Issue by sabbelasichon** [sascha-egerer/phpstan-typo3#24]
I am always adding the configuration https://phpstan.org/writing-php-code/solving-undefined-variables to phpstan.neon for different kind of methods.
Example: 
```yaml
parameters:
    earlyTerminatingMethodCalls:
        TYPO3\CMS\Extbase\Mvc\Controller\AbstractController:
            - redirectToUri
            - redirect
            - forward
            - forwardToReferringRequest
        TYPO3\CMS\Core\Utility\HttpUtility:
            - redirect
````
I would like to add this to your repo so it can help everyone else in the future. What do you think?
