### ISSUE TITLE
[Bug] Class path shouldn't start with \ in mapping

### ISSUE THREAD

**Issue by tlueder** [sascha-egerer/phpstan-typo3#54]
Hi,

While working on https://github.com/sascha-egerer/phpstan-typo3/pull/51 and https://github.com/sascha-egerer/phpstan-typo3/pull/53 I noticed a strange behaviour. And got mixed types where I shouldn't have.

The problem was that I used the config for contextApiGetAspectMapping as a template and also wrote the class paths in the same way.

As long as you only use this to check the return type of 
`
context->getAspect() 
`
it works fine (what I believe is an error in it self), but as soon as you do something like 
`
context->getAspect('frontend.user')->isAdmin() 
`
and check the type on that....  All hell breaks loose.

TL:DR

```
        contextApiGetAspectMapping:
            date: \TYPO3\CMS\Core\Context\DateTimeAspect
            visibility: \TYPO3\CMS\Core\Context\VisibilityAspect
            backend.user: \TYPO3\CMS\Core\Context\UserAspect
            frontend.user: \TYPO3\CMS\Core\Context\UserAspect
            workspace: \TYPO3\CMS\Core\Context\WorkspaceAspect
            language: \TYPO3\CMS\Core\Context\LanguageAspect
            typoscript: \TYPO3\CMS\Core\Context\TypoScriptAspect
```

Should be

```
        contextApiGetAspectMapping:
            date: TYPO3\CMS\Core\Context\DateTimeAspect
            visibility: TYPO3\CMS\Core\Context\VisibilityAspect
            backend.user: TYPO3\CMS\Core\Context\UserAspect
            frontend.user: TYPO3\CMS\Core\Context\UserAspect
            workspace: TYPO3\CMS\Core\Context\WorkspaceAspect
            language: TYPO3\CMS\Core\Context\LanguageAspect
            typoscript: TYPO3\CMS\Core\Context\TypoScriptAspect
```
